bf2fc6cc711aee1a0c2a/kas-installer

- operators/kas-fleetshard/resources/kas-fleetshard-operator.yml
- operators/kas-fleetshard/resources/kas-fleetshard-sync.yml
Adding these selectors to match the same config as prod: https://github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/blob/main/resources/prometheus/pod_monitors/kas-fleetshard-sync-metrics.yaml#L10
> Adding new label for kas-fleetshard-operator and kas-fleetshard-sync pods

- README.md
With the latest release of the rhoas cli we did removed deprecated flag to skip terms check.
Now we need to skip many things like kafka sizes validation etc. 
New flag is: bypass-checks
> fix: update flag to bypass-checks

- kas-fleet-manager/deploy-kas-fleet-manager.sh
The latest Observability Operator release ([v3.0.10](https://github.com/redhat-developer/observability-operator/releases/tag/v3.0.10)) includes SMTP support to send emails for warning severity alerts. Once this version of the Operator is used within the kas-installer (currently it's using 3.0.9), we want to disable SMTP just as we disable PagerDuty and DeadMansSnitch.
> Disable observability SMTP

- managed_kafka.sh
- utils/common.sh
This enables use-cases involving bearer tokens where the client needs to trust both keycloak server (secured by public CA provided by OpenShift) and the kafka server (protected by self-signed cert).
> Add JVM platform trust to truststore.

- rhoas_login.sh
Switching to `command` based on https://stackoverflow.com/a/677212/1389220
I've done a very limited check on linux.
I only discovered that rhoas_login had support for copying to the clipboard as I was poking it for something else (it fails unless you've run `oc login`) it was failing because the output of `which` was being sent to `/dev/null` so `COPYCMD` was always empty.
> Correctly detect if the app to copy to the clipboard.

- kas-installer.sh
Use `${SSO_TRUSTED_CA}` if set (even when blank), otherwise use `${MAS_SSO_CERTS}`. Allows us to disable having the CP pass the cert to the DP.
> Allow for SSO trusted certificate to be set to blank (disabled)

- README.md
- kas-fleet-manager/deploy-kas-fleet-manager.sh
What I did in this PR:
1. add `yq` as prerequisites in README
2. output logs when `kas-fleet-manager-service-template-params` or `kas-fleet-manager-secrets-template-params` has no executable permission.
> warn fleet manager custom file has no permission

- managed_kafka.sh
- service_account.sh
- utils/common.sh
Improves the script by ensuring that it is fail fast/fail clearly when programs it invokes fail.
I tested the create/delete/list/get/patch/certgen use-cases.  The aim was for compatibility with existing use-cases.
> managed_kafka.sh - use set -euo pipefail

- kas-installer-defaults.env
running the example command ended in "invalid input" because my token isn't padded
> accounting for token base64 padding

- README.md
- managed_kafka.sh
- tool_access.sh
@MikeEdgar for usage with the instance profiler it seems handy to automate the 1/2 steps for tool access.  If it seems ok, I can further refine it and the README.
Also would there be any objection to adding bootstrap.servers=<bootstrap_server_host> into the app-services.properties?
> adding a script for tool access

- rhoas_login.sh
Latest verison of `rhoas` rejects the `--mas-auth-url` argument.
> Remove use of mas_auth_url parameter

- kas-installer-defaults.env
@k-wall   Can you approve this?
Observability tag: https://github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/releases/tag/v1.40.1
> Bump observability resources to v1.40.1

- operators/generate-kas-fleetshard-olm-bundle.sh
Since all our images are running in linux/amd64 platform, we need to force docker to build linux/amd64 compatible images. Without this patch, the M1 mac will fail to deploy the fleetshard operator due to the error:
```
State:         Waiting
Reason:      CrashLoopBackOff
Last State:    Terminated
Reason:      Error
Message:     exec /bin/opm: exec format error
```
Note: It won't impact any non-arm64 chip users because they will build with linux/amd64 originally.
ref: https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
> set docker env variable to force it build images for linux/amd64 platform

- kas-fleet-manager/deploy-kas-fleet-manager.sh
This will print `ManagedKafkaAgents/managed-agent failed to become ready: Observability secret not yet accepted` when the secret has not been accepted and the prior `wait` command times out.
> [MGDSTRM-9660] Display message when MK agent fails to become ready

- README.md
Why:
On a kas-installer OSD cluster the e2e tests were failing with the config generated by this script because there was no https route to the admin service.
> update e2e testing doc to direct user to enable adminserver tls

- kas-fleet-manager/deploy-kas-fleet-manager.sh
kas-installer relied on a soon to be removed KFM feature that resetted the standalone cluster status to "cluster_provisioning" to allow for terraforming phase to take place. That's why it was okay to set the status of standalone cluster to "ready" as it was reset to "provisioning" no matter what. But this KFM capability didn't take onto account that someone can have an already terraformed cluster and set their status to "ready" meaning that KFM doesn't have to auto terraform the cluster. With the change in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1355 and notably the
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1355/commits/acdaa4db9f39369fbe799b75ee05311a8c72d27d commit, KFM wont change the status if they are different from "accepted" so …
> fix(kas-fleet-manager): ensure that the cluster status is cluster_provisioned

- kas-fleet-manager/deploy-kas-fleet-manager.sh
Minor improvement to the KFM install script.
1. use `git reset` to update a branch pointer, required when the remote has been force pushed
> Use git reset instead of git pull for branch update

- kas-fleet-manager/deploy-kas-fleet-manager.sh
- kas-installer.sh
main fails like this for me:
```
./kas-installer.sh
./kas-installer.sh: line 43: ${ENTERPRISE_ENABLED,,}: bad substitution
```
> kas-installer: bad substitution

- README.md
- kas-installer-defaults.env
The parameter is removed in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1573 as it is no longer needed because KFM infers it from the supplied quota configuration
> docs: remove mentions of ENTERPRISE_CLUSTER_REGISTRATION_ALLOWED_ORGANIZATIONS

- kas-fleet-manager/deploy-kas-fleet-manager.sh
Support for Observatorium DEX authentication has been removed from KAS Fleet Manager.
Related to https://issues.redhat.com/browse/MGDSTRM-10990
> remove KFM DEX parameter references
