kas-fleet-manager/deploy-kas-fleet-manager.sh
Fixes #141 ; cherry-picked from #137
=> Set data plane client_id in kas-fleet-manager's database

README.md, kas-fleet-manager/deploy-kas-fleet-manager.sh, kas-installer.env.example, kas-installer.sh
Also make login a pre-requisite step
/cc @MikeEdgar @JameelB would love your feedback on this.
=> feat: allow to configured supported cloud_provider region

CONTRIBUTING.md, LICENSE, dco.txt
Signed-off-by: Ramesh Reddy <rareddy@jboss.org>
=> Adding license files to the repo

operators/install-strimzi-cluster-operator.sh, operators/kas-fleetshard/resources/kas-fleetshard-operator.yml, operators/kas-fleetshard/resources/kas-fleetshard-sync.yml, operators/kas-fleetshard/resources/managedkafkas.managedkafka.bf2.org-v1.yml
Signed-off-by: Michael Edgar <medgar@redhat.com>
=> Update data plane to rhosak bundle 0.0.15, kas-fleetshard 0.21.0

README.md
=> Add instance type configuration instructions

README.md, login-all.sh, rhoas_login.sh
- Improve rhoas_login with clipboard copy and dryrun
- Safe login script
- Add doc on login-all.sh
=> Improve login scripts

kas-fleet-manager/deploy-kas-fleet-manager.sh, kas-installer-defaults.env
Bump to kas-fleet-manager @ 5342ce8, remove `yq` dependency
=> [MGDSTRM-8518] Await managed-agent readiness before exiting script

README.md, kas-installer-defaults.env, operators/generate-kas-fleetshard-olm-bundle.sh
Also updates kas-fleetshard-operator to latest prod release.
=> [MGDSTRM-8539] Add script to build fleetshard and generate OLM bundle

kas-fleet-manager/deploy-kas-fleet-manager.sh, uninstall.sh
- Remove observability CR before OLM resources
Signed-off-by: Michael Edgar <medgar@redhat.com>
=> Minor adjustments to waits/retries during KFM installation

.gitignore, README.md, kas-installer.sh, mas-sso/keycloak.yaml, mas-sso/mas-sso-installer.sh, mas-sso/sso-template.yaml
WHAT
Support customization of MAS-SSO deployment resources
WHY
Support smaller machine pools for less-demanding testing
In support of MGDSTRM-8542
=> Support configuration for MAS-SSO resources; tune status checks

kas-installer-defaults.env
Catches up with current state of stage/prod.
=> Bump observability to v1.36.0

operators/generate-kas-fleetshard-olm-bundle.sh, operators/uninstall-kas-fleetshard.sh, operators/uninstall-strimzi-cluster-operator.sh, uninstall.sh
=> Support reserved deployment PriorityClass from kas-fleetshard K8s file

e2e-test-config.sh
Set E2E variables depending on SSO environment
=> Set E2E variables depending on SSO environment

kas-installer-defaults.env
Signed-off-by: Vanessa Busch <vbusch@redhat.com>
=> Bump kas-fleetshard bundle (fleetshard 0.28.0)

README.md, kas-installer-defaults.env
Bumping KFM inmage tag to a5eb456
=> bump KFM image tag to a5eb456

kas-installer-defaults.env
simplify the incantation for fetching the user id and org id from ocm token
=> simplify example to fetch user/org ID from ocm

kas-installer-defaults.env
Bump RHOSAK bundle to v4.10-v0.1.6-2
=> bump-rhosak-bundle-v4.10-v0.1.6-2

kas-installer-defaults.env
Signed-off-by: Vanessa Busch <vbusch@redhat.com>
=> bump rhosak-bundle v10-v0.1.7-2

kas-fleet-manager/deploy-kas-fleet-manager.sh
=> fix: cannot scale the kas-fleet-manager deployment down during install

kas-installer-defaults.env
I guess this also closes #239.
=> Update to v1.42.0 of observability-resources-mk

kas-installer-defaults.env
Tag: https://github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/releases/tag/v1.43.0
=> Update to v1.43.0 of observability-resources-mk

observatorium/.gitignore, observatorium/resources/crd.yml, observatorium/resources/operator/bases/crd.yaml
Closes #242
+ .gitignore files generated during installation of Observatorium and its dependencies (dex, minio).
=> update observatorium crds to apiextensions.k8s.io/v1

kas-installer-defaults.env
MGDSTRM-9941 strimzi-canary 0.6.0 - Have the consuming client refresh its metadata if the partition leadership changes.
=> MGDSTRM-10418: Updating to latest RHOSAK bundle release (v0.1.9)

README.md, gen_certs.sh, kas-fleet-manager/deploy-kas-fleet-manager.sh, kas-installer-defaults.env, kas-installer.sh
For #266
Signed-off-by: Michael Edgar <medgar@redhat.com>
=> [MGDSTRM-10599] Enterprise enhancements & update KFM to `7f968f0`

kas-installer-defaults.env, operators/generate-kas-fleetshard-olm-bundle.sh
- Bumps kas-fleetshard to v1.0.18 (operator version 0.34.0)
- Incorporates changes from https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/247
- Fixes https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/issues/237
Depends on merge of https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/pull/871
=> [MGDSTRM-10719] Adjust bundle script for kas-fleetshard bundle module

kas-installer-defaults.env
This makes the use of Strimzi PodSets the default.
=> MGDSTRM-10704: Bump RHOSAK bundle (0.11.1)

kas-installer-defaults.env
MGDSTRM-10777: KafkaTopicPartitionReplicaSpreadMax firing during broker reboots
MGDSTRM-10459: Alert on unexpected haproxy configuration reloads (that drop connections)
MGDSTRM-9927: unsuccessful logins - exporting *_total instead of *_rate metric
=> Bump observability to v1.50.0

kas-installer-defaults.env
bump OBSERVABILITY_CONFIG_TAG to v1.50.3
=> bump OBSERVABILITY_CONFIG_TAG to v1.50.3

operators/generate-kas-fleetshard-olm-bundle.sh
Example on Wiki page updated: https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/wiki/Deploying-kas-fleetshard-from-Source#example
=> Add support for KFO bundle patch-file in OLM bundle generation script

kas-fleet-manager/deploy-kas-fleet-manager.sh
For consistency, avoid assumption that `oc` context is the KFM namespace.
=> Specify namespace for all KFM kube commands
